driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: fedora-28
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: sles-11.2
    driver_config:
      box: chef/sles-11-sp2-x86_64
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
# Solaris 10 requires the release directory from the  OS ISO to be in `/var/spool/pkg`
# in order for the converge to succeed.
  - name: solaris-10.11
    driver_config:
      box: chef/solaris-10.11
  - name: solaris-11.3
    driver_config:
      box: chef/solaris-11.3
  - name: macosx-10.11
    driver_config:
      box: chef/macosx-10.10
  - name: macosx-10.12
    driver_config:
      box: chef/macosx-10.10

suites:
  - name: default
    run_list: ntp::default
    attributes:
      ntp:
        sync_clock: true
