name              'ntp'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures ntp as a client or server'
version           '3.12.4'
source_url        'https://github.com/sous-chefs/ntp'
issues_url        'https://github.com/sous-chefs/ntp/issues'
chef_version      '>= 12.15'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'gentoo'
supports 'mac_os_x'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'solaris2'
supports 'ubuntu'
supports 'windows'
